# Generated by Django 2.2.7 on 2019-11-09 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 5, 25, 54, 496269, tzinfo=utc), help_text='creation datetime', verbose_name='created'),
        ),
        migrations.AddField(
            model_name='hero',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='last modified datetime', verbose_name='modified'),
        ),
    ]
