# Generated by Django 2.2.7 on 2019-11-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteplan',
            name='user',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
