# Generated by Django 2.2.7 on 2019-11-09 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20191109_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 6, 18, 15, 611031, tzinfo=utc), help_text='creation datetime', verbose_name='created'),
        ),
    ]
