# Generated by Django 2.2.7 on 2019-11-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20191109_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
