# Generated by Django 2.2.7 on 2019-11-10 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0004_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_from', models.CharField(max_length=30)),
                ('journey_to', models.CharField(max_length=30)),
                ('journey_date', models.DateTimeField(default=datetime.datetime(2019, 11, 10, 7, 0, 38, 197197, tzinfo=utc))),
            ],
            options={
                'db_table': 'journey',
            },
        ),
    ]
